name: ci test
on:
  push:
jobs:
  build-test-lint:
    strategy:
        matrix:
          version: [18.15]
    permissions:
      packages: read
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Start LocalStack
      run: |
        pip install localstack awscli-local[ver1]
        docker pull localstack/localstack
        localstack start -d
        echo "Localstack starting..."
        localstack wait -t 30
        echo "Localstack started."
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
    - name: yarn installation
      run: yarn
    - name: test files
      run: yarn jest --verbose
